# Site settings
author: Matthew Im
title: Coding Journey
header-img: img/home-bg.png
email: matthew.seiim@gmail.com
copyright_name: Matthew Im
description: > # this means to ignore newlines until "baseurl:"
  Coding Path
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jsm125

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
